language: java
jdk:
  - oraclejdk8

install: true
script:
  - mvn clean install
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token

cache:
  directories:
    - '$HOME/.m2/repository'
